/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_text_free(a: number): void;
export function text_new(a: number, b: number, c: number, d: number): number;
export function text_set_text(a: number, b: number, c: number): void;
export function text_get_text(a: number, b: number): void;
export function text_set_color(a: number, b: number, c: number): void;
export function text_get_color(a: number, b: number): void;
export function text_get_id(a: number, b: number): void;
export function text_set_id(a: number, b: number, c: number): void;
export function text_as_element(a: number): number;
export function __wbg_button_free(a: number): void;
export function button_new(a: number): number;
export function button_set_text(a: number, b: number): void;
export function button_get_text(a: number): number;
export function button_get_id(a: number, b: number): void;
export function button_set_id(a: number, b: number, c: number): void;
export function button_as_element(a: number): number;
export function button_on_click(a: number, b: number): void;
export function __wbg_element_free(a: number): void;
export function element_get_type_name(a: number, b: number): void;
export function element_get_ptr(a: number): number;
export function element_get_js_ptr(a: number): number;
export function __wbg_app_free(a: number): void;
export function app_create_app(a: number, b: number, c: number): number;
export function app_start(a: number, b: number, c: number, d: number): void;
export function app_get_by_id_element(a: number, b: number, c: number): number;
export function __wbg_view_free(a: number): void;
export function __wbg_get_view_width(a: number): number;
export function __wbg_set_view_width(a: number, b: number): void;
export function __wbg_get_view_height(a: number): number;
export function __wbg_set_view_height(a: number, b: number): void;
export function view_new(a: number, b: number): number;
export function view_add_child_view(a: number, b: number): void;
export function view_add_child_label(a: number, b: number): void;
export function view_add_child_link(a: number, b: number): void;
export function view_add_child_input(a: number, b: number): void;
export function view_add_child_button(a: number, b: number): void;
export function view_add_child_image(a: number, b: number): void;
export function view_get_id(a: number, b: number): void;
export function view_set_id(a: number, b: number, c: number): void;
export function view_as_element(a: number): number;
export function __wbg_label_free(a: number): void;
export function label_new(a: number): number;
export function label_set_text(a: number, b: number): void;
export function label_get_text(a: number): number;
export function label_get_id(a: number, b: number): void;
export function label_set_id(a: number, b: number, c: number): void;
export function label_as_element(a: number): number;
export function __wbg_image_free(a: number): void;
export function __wbg_get_image_width(a: number): number;
export function __wbg_set_image_width(a: number, b: number): void;
export function __wbg_get_image_height(a: number): number;
export function __wbg_set_image_height(a: number, b: number): void;
export function image_new(): number;
export function image_set_data(a: number, b: number, c: number, d: number, e: number): void;
export function image_get_data(a: number, b: number): void;
export function image_get_id(a: number, b: number): void;
export function image_set_id(a: number, b: number, c: number): void;
export function image_as_element(a: number): number;
export function __wbg_link_free(a: number): void;
export function link_new(a: number, b: number, c: number): number;
export function link_set_text(a: number, b: number): void;
export function link_get_text(a: number): number;
export function link_set_url(a: number, b: number, c: number): void;
export function link_get_url(a: number, b: number): void;
export function link_get_id(a: number, b: number): void;
export function link_set_id(a: number, b: number, c: number): void;
export function link_as_element(a: number): number;
export function __wbg_input_free(a: number): void;
export function input_new(a: number, b: number): number;
export function input_set_text(a: number, b: number, c: number): void;
export function input_get_text(a: number, b: number): void;
export function input_get_id(a: number, b: number): void;
export function input_set_id(a: number, b: number, c: number): void;
export function input_as_element(a: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hd59f5e83f90fe7d4(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h43aa5fe6afdb8687(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h63fd760bc3a1f2f5(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h9dec9fe7658d82bf(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h84b34f985ebe8e14(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hfa76d001ba0ad1ac(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h8d35d13216d0ad10(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha8f03f3742ce8c3f(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h74d2971fb27934c1(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h6f3e5fa77e4b8f50(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
