/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_app_free(a: number): void;
export function app_create_app(a: number, b: number, c: number): number;
export function app_start(a: number, b: number, c: number, d: number): void;
export function __wbg_link_free(a: number): void;
export function link_new(a: number, b: number, c: number, d: number): number;
export function link_set_text(a: number, b: number, c: number): void;
export function link_get_text(a: number, b: number): void;
export function link_set_url(a: number, b: number, c: number): void;
export function link_get_url(a: number, b: number): void;
export function link_get_id(a: number, b: number): void;
export function link_set_id(a: number, b: number, c: number): void;
export function __wbg_label_free(a: number): void;
export function label_new(a: number, b: number): number;
export function label_set_text(a: number, b: number, c: number): void;
export function label_get_text(a: number, b: number): void;
export function label_get_id(a: number, b: number): void;
export function label_set_id(a: number, b: number, c: number): void;
export function __wbg_view_free(a: number): void;
export function view_new(a: number, b: number): number;
export function view_add_child_view(a: number, b: number): void;
export function view_add_child_label(a: number, b: number): void;
export function view_add_child_link(a: number, b: number): void;
export function view_get_id(a: number, b: number): void;
export function view_set_id(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h2040c96be8790959(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h77cb1a18c8f553e4(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hde178ac014ce8250(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h9ba1e368b45a6783(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf9e8773c47c1865d(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h3354795b29bf21c9(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h993d75df6d212d24(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha004a85c37ffa1b2(a: number, b: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h97f6282cfae9d8f0(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h22b10cbf549f66aa(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
